global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'currency-rate-provider'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['currency-rate-provider:8081']
        labels:
          instance: 'currency-rate-provider'

  - job_name: 'rate-printer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rate-printer:8082']
        labels:
          instance: 'rate-printer'

  - job_name: 'zookeeper'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['zookeeper:7000']
        labels:
          instance: 'zookeeper'
