# ????????? ??????? Spring Boot
server.port=8082

# ????????? gRPC ???????
grpc.client.host=localhost
grpc.client.port=9090

# ????????? ???????????
logging.level.root=INFO
logging.level.com.example.rateprinter=DEBUG
logging.pattern.console=[%d{yyyy-MM-dd HH:mm:ss}] [%thread] %-5level %logger{36} - %msg%n
